empaquetar:
  image: alpine
  before_script:
    - apk add --update zip curl
  script:
    - zip -r content.zip .
    - 'curl 
        --header "JOB-TOKEN: $CI_JOB_TOKEN"
        --upload-file content.zip
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Content/1.0.0/content.zip"'